add default for account struct
cloudflare/cloudflare-rs pull request #115
Opened 2020-03-28 06:38 UTC by shalzz

2020-11-20 01:21 UTC, sssilver commented on cloudflare/src/endpoints/account/mod.rs
> +    #[serde(default = "default_time")]
What's the value of having the time when account was created default to now()?

2020-11-20 01:38 UTC, adamchalmers requested changes
Rather than add defaults for the Account struct, I'd rather we change the [Zone::account](https://docs.rs/cloudflare/0.6.6/cloudflare/endpoints/zone/struct.Zone.html#structfield.account) field so that it's no longer of type Account, but rather some new type with only `id` and `name`, probably named `AccountDetails` or `AccountIdName`.

2020-11-25 16:42 UTC, adamchalmers approved these changes

2020-11-25 16:55 UTC, nataliescottdavidson approved these changes

2020-11-25 17:36 UTC, ashleymichal approved these changes

2020-11-25 17:37 UTC, merged