New endpoint for creating Named Argo Tunnels
cloudflare/cloudflare-rs pull request #130
Opened 2020-12-03 17:29 UTC by nmldiegues

2020-12-03 18:56 UTC, adamchalmers requested changes

2020-12-03 18:56 UTC, adamchalmers commented on cloudflare/src/endpoints/argo_tunnel/create_tunnel.rs
> +pub struct CreateTunnelParams<'a> {
I suggest naming this Params, so that users can write `create_tunnel::Params`. Like the example of `create_pool::Params`.

2020-12-03 18:56 UTC, adamchalmers commented on cloudflare/src/endpoints/argo_tunnel/mod.rs
> +pub struct Tunnel {
Suggestion/nit: Move these into a `data_structures.rs` file in this module, and then have this mod.rs `pub use datastructures::*` so all the datatypes are in the main `argo_tunnel` namespace.

2020-12-04 16:38 UTC, adamchalmers approved these changes

2020-12-04 16:38 UTC, adamchalmers commented
LGTM

2020-12-07 10:49 UTC, nmldiegues commented on cloudflare/src/framework/json_utils.rs
> +            write!(formatter, "base64 ASCII text")
This method is not the "interesting" part. It is used only to create an error message stating what is expected during deserialization, such that if the method below fails or is never called by the "AST traversal", then this one is invoked.

See https://docs.serde.rs/serde/de/trait.Visitor.html#tymethod.expecting

And yes, "base64 ASCII text" is the error message that would appear under an error that says:
```
This Visitor expects to receive base64 ASCII text
```
in the context of a serde error.

2020-12-07 10:56 UTC, chungthuang approved these changes

2020-12-07 11:01 UTC, merged