Release 0.9.2
cloudflare/cloudflare-rs pull request #181
Opened 2022-03-21 17:52 UTC by nmldiegues

Same as https://github.com/cloudflare/cloudflare-rs/pull/180
0.9.1. did not do anything because I tagged it wrong (it should had been v0.9.1)

2022-03-21 17:54 UTC, Noah-Kennedy requested changes
We shouldn't bump without a corresponding release. Can you revert the other one and bump back to 0.9.1?

2022-03-21 17:56 UTC, nmldiegues commented
> We shouldn't bump without a corresponding release. Can you revert the other one and bump back to 0.9.1?

Why not? Releases are free. This way there's less confusion/entropy as we move forward.

2022-03-22 06:59 UTC, sssilver approved these changes

2022-03-22 15:13 UTC, nmldiegues commented
Will re-issue a new release with https://github.com/cloudflare/cloudflare-rs/pull/174

2022-03-22 15:13 UTC, closed without merging